spring:
  application:
    name: discount-service
  datasource:
    url: jdbc:postgresql://localhost:5432/E-CommerceDB
    username: postgres
    password: qwerty123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8082

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

jwt:
  secret: 12345678901234567890123456789012