
spring:
  application:
    name: order-service
  datasource:
    url: jdbc:postgresql://localhost:5432/E-CommerceDB
    username: postgres
    password: qwerty123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8084

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka


#resilience4j configuration
resilience4j:
  circuitbreaker:
    instances:
      discountService:
        registerHealthIndicator: true
        failureRateThreshold: 50
        slidingWindowSize: 5
        waitDurationInOpenState: 5s
  retry:
    instances:
      discountService:
        maxAttempts: 3
        waitDuration: 500ms

jwt:
  secret: mysecurekey1234567890abcdef12345678
  #mysecurekey1234567890abcdef12345678