spring:
  application:
    name: cart-service
  datasource:
    url: jdbc:postgresql://localhost:5432/E-CommerceDB
    username: postgres
    password: qwerty123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  kafka:
    bootstrap-servers: localhost:9092

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: false
    fetch-registry: false
server:
  port: 8083

resilience4j:
  circuitbreaker:
    instances:
      catalogueService:
        registerHealthIndicator: true
        slidingWindowSize: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 5s
  retry:
    instances:
      catalogueService:
        maxAttempts: 3
        waitDuration: 500ms



jwt:
  secret: 12345678901234567890123456789012